### ISSUE TITLE
Ble and Wifi Together

### ISSUE THREAD

**Issue by tcpipchip** [wiredlab/esp32-ble-scan-mqtt#1]
Dont you have problems ? (Panic Reset)

Miguel

**Comment by tcpipchip** [comment]
Hi, it working!

Is it possibible add to the payload the manufacturer data ?
You are showing
{"time":"2020-11-06T20:59:57Z","mac":"282c02403d9b","payload":"0201060d094566656e746f53656e736f72","name":"EfentoSensor","rssi":-51}
and my BLE scanner is showing the correct data
![image](https://user-images.githubusercontent.com/11488460/98414378-04867c00-205a-11eb-8c05-6b8c5abe2b6b.png)

**Comment by etihwnad** [comment]
Hi @tcpipchip, thank you for your comment.

Many BLE devices will transmit several different advertisement payloads.  This code is mostly meant for finding addresses ("mac") of devices and doesn't return every payload that is heard by default.

The variable `KEEP_DUPLICATES` is `false` in the example `config.h` file.  When `false`, the system will only report the **first** payload from a particular address heard in the scan interval `BLE_SCAN_TIME` (default of 10 seconds).

Change `KEEP_DUPLICATES` to `true` to get **every** payload that is heard.


If we want or need to extract information from the payload, we just decode the raw payload data later.  This keeps the sniffer simple.

A nice overview of how a payload is encoded is at https://www.argenox.com/library/bluetooth-low-energy/ble-advertising-primer/

This BLE advertisement payload `0201060d094566656e746f53656e736f72` contains two elements:

```
element:
    len: 0x02
    type: 0x01 (flags)
    data: 0x06 or 0b0000 0110  (LE General Discoverable Mode, and BR/EDR not supported)
element:
    len: 0x0d (13 bytes)
    type: 0x09 (Complete Local Name)
    data: 0x4566656e746f53656e736f72 (12 bytes)
        ascii-decoded: "EfentoSensor"
```


If you want the Manufacturer Data in the JSON output directly, you can also add the following to the callback function:


```cpp
      if (advertisedDevice.haveManufacturerData()) {
        msg.concat("\"mfgdata\":\"");
        msg.concat(advertisedDevice.getManufacturerData().c_str());
        msg.concat("\",");
      }
```
